name: Run static analysis

on:
  workflow_dispatch:

jobs:
  static_analysis_master:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/static_analysis.yml@master
    secrets: inherit
    with:
      branch: master
      actions_branch: master
  static_analysis_dev:
    uses: Prusa-Development/PrusaSlicer-Actions/.github/workflows/static_analysis.yml@master
    secrets: inherit
    with:
      branch: ms_dev
      actions_branch: master
